// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using movie_rating_platform.Services.Database;

#nullable disable

namespace movie_rating_platform.Services.Migrations
{
    [DbContext(typeof(MovieRatingDBContext))]
    partial class MovieRatingDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("movie_rating_platform.Services.Database.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActorId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            DateOfBirth = new DateTime(1943, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            IsDeleted = false,
                            LastName = "De Niro"
                        },
                        new
                        {
                            ActorId = 2,
                            DateOfBirth = new DateTime(1937, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Morgan",
                            IsDeleted = false,
                            LastName = "Freeman"
                        },
                        new
                        {
                            ActorId = 3,
                            DateOfBirth = new DateTime(1984, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Scarlett",
                            IsDeleted = false,
                            LastName = "Johansson"
                        },
                        new
                        {
                            ActorId = 4,
                            DateOfBirth = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Leonardo",
                            IsDeleted = false,
                            LastName = "DiCaprio"
                        },
                        new
                        {
                            ActorId = 5,
                            DateOfBirth = new DateTime(1981, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Natalie",
                            IsDeleted = false,
                            LastName = "Portman"
                        },
                        new
                        {
                            ActorId = 6,
                            DateOfBirth = new DateTime(1956, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tom",
                            IsDeleted = false,
                            LastName = "Hanks"
                        },
                        new
                        {
                            ActorId = 7,
                            DateOfBirth = new DateTime(1988, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emma",
                            IsDeleted = false,
                            LastName = "Stone"
                        },
                        new
                        {
                            ActorId = 8,
                            DateOfBirth = new DateTime(1963, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brad",
                            IsDeleted = false,
                            LastName = "Pitt"
                        },
                        new
                        {
                            ActorId = 9,
                            DateOfBirth = new DateTime(1982, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anne",
                            IsDeleted = false,
                            LastName = "Hathaway"
                        },
                        new
                        {
                            ActorId = 10,
                            DateOfBirth = new DateTime(1954, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Denzel",
                            IsDeleted = false,
                            LastName = "Washington"
                        });
                });

            modelBuilder.Entity("movie_rating_platform.Services.Database.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<double?>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MovieType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            AverageRating = 4.0,
                            CoverImage = "/images/movie1.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(1994, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Hope is a dangerous thing.",
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            MovieId = 2,
                            AverageRating = 3.5,
                            CoverImage = "/images/movie2.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "An offer you can't refuse.",
                            Title = "The Godfather"
                        },
                        new
                        {
                            MovieId = 3,
                            AverageRating = 4.5,
                            CoverImage = "/images/movie3.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Why so serious?",
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 4,
                            AverageRating = 2.5,
                            CoverImage = "/images/movie4.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Multiple stories collide.",
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            MovieId = 5,
                            AverageRating = 3.0,
                            CoverImage = "/images/movie5.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(1999, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "First rule: don't talk about it.",
                            Title = "Fight Club"
                        },
                        new
                        {
                            MovieId = 6,
                            AverageRating = 4.7000000000000002,
                            CoverImage = "/images/movie6.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Dream within a dream.",
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 7,
                            AverageRating = 3.2000000000000002,
                            CoverImage = "/images/movie7.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(1994, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Life is like a box of chocolates.",
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            MovieId = 8,
                            AverageRating = 3.7999999999999998,
                            CoverImage = "/images/movie8.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "What is the Matrix?",
                            Title = "The Matrix"
                        },
                        new
                        {
                            MovieId = 9,
                            AverageRating = 4.2999999999999998,
                            CoverImage = "/images/movie9.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Love transcends time and space.",
                            Title = "Interstellar"
                        },
                        new
                        {
                            MovieId = 10,
                            AverageRating = 4.0999999999999996,
                            CoverImage = "/images/movie10.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Are you not entertained?",
                            Title = "Gladiator"
                        },
                        new
                        {
                            MovieId = 11,
                            AverageRating = 3.7000000000000002,
                            CoverImage = "/images/movie11.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(2006, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Every magic trick has a cost.",
                            Title = "The Prestige"
                        },
                        new
                        {
                            MovieId = 12,
                            AverageRating = 3.8999999999999999,
                            CoverImage = "/images/movie12.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(2006, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Cops and moles collide.",
                            Title = "The Departed"
                        },
                        new
                        {
                            MovieId = 13,
                            AverageRating = 4.2000000000000002,
                            CoverImage = "/images/movie13.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(2014, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Not quite my tempo.",
                            Title = "Whiplash"
                        },
                        new
                        {
                            MovieId = 14,
                            AverageRating = 2.8999999999999999,
                            CoverImage = "/images/movie14.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Put on a happy face.",
                            Title = "Joker"
                        },
                        new
                        {
                            MovieId = 15,
                            AverageRating = 3.6000000000000001,
                            CoverImage = "/images/movie15.jpg",
                            IsDeleted = false,
                            MovieType = 0,
                            ReleaseDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Life, liberty, and revenge.",
                            Title = "Django Unchained"
                        },
                        new
                        {
                            MovieId = 16,
                            AverageRating = 4.0,
                            CoverImage = "/images/tvshow1.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2008, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Say my name.",
                            Title = "Breaking Bad"
                        },
                        new
                        {
                            MovieId = 17,
                            AverageRating = 3.2999999999999998,
                            CoverImage = "/images/tvshow2.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2016, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Upside Down awaits.",
                            Title = "Stranger Things"
                        },
                        new
                        {
                            MovieId = 18,
                            AverageRating = 4.5,
                            CoverImage = "/images/tvshow3.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2011, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Winter is coming.",
                            Title = "Game of Thrones"
                        },
                        new
                        {
                            MovieId = 19,
                            AverageRating = 3.6000000000000001,
                            CoverImage = "/images/tvshow4.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2005, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "World's best boss.",
                            Title = "The Office"
                        },
                        new
                        {
                            MovieId = 20,
                            AverageRating = 3.7000000000000002,
                            CoverImage = "/images/tvshow5.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(1994, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "I'll be there for you.",
                            Title = "Friends"
                        },
                        new
                        {
                            MovieId = 21,
                            AverageRating = 4.7999999999999998,
                            CoverImage = "/images/tvshow6.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2016, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Inside royal life.",
                            Title = "The Crown"
                        },
                        new
                        {
                            MovieId = 22,
                            AverageRating = 4.0,
                            CoverImage = "/images/tvshow7.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "This is the way.",
                            Title = "The Mandalorian"
                        },
                        new
                        {
                            MovieId = 23,
                            AverageRating = 3.8999999999999999,
                            CoverImage = "/images/tvshow8.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2019, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Toss a coin to your Witcher.",
                            Title = "The Witcher"
                        },
                        new
                        {
                            MovieId = 24,
                            AverageRating = 4.4000000000000004,
                            CoverImage = "/images/tvshow9.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2013, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "By order of the Peaky Blinders.",
                            Title = "Peaky Blinders"
                        },
                        new
                        {
                            MovieId = 25,
                            AverageRating = 3.7999999999999998,
                            CoverImage = "/images/tvshow10.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2019, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Superheroes gone bad.",
                            Title = "The Boys"
                        },
                        new
                        {
                            MovieId = 26,
                            AverageRating = 3.7000000000000002,
                            CoverImage = "/images/tvshow11.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2020, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Chess prodigy rises.",
                            Title = "The Queen's Gambit"
                        },
                        new
                        {
                            MovieId = 27,
                            AverageRating = 4.2999999999999998,
                            CoverImage = "/images/tvshow12.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Survive and protect.",
                            Title = "The Last of Us"
                        },
                        new
                        {
                            MovieId = 28,
                            AverageRating = 3.5,
                            CoverImage = "/images/tvshow13.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2015, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Legal trouble ahead.",
                            Title = "Better Call Saul"
                        },
                        new
                        {
                            MovieId = 29,
                            AverageRating = 4.0999999999999996,
                            CoverImage = "/images/tvshow14.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2022, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Fire and blood.",
                            Title = "House of the Dragon"
                        },
                        new
                        {
                            MovieId = 30,
                            AverageRating = 3.8999999999999999,
                            CoverImage = "/images/tvshow15.jpg",
                            IsDeleted = false,
                            MovieType = 1,
                            ReleaseDate = new DateTime(2021, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "God of Mischief returns.",
                            Title = "Loki"
                        });
                });

            modelBuilder.Entity("movie_rating_platform.Services.Database.MovieActor", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 9,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 9,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 10,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 10,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 11,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 11,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 12,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 12,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 13,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 13,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 14,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 14,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 15,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 15,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 16,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 16,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 17,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 17,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 18,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 18,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 19,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 19,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 20,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 20,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 21,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 21,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 22,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 22,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 23,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 23,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 24,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 24,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 25,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 25,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 26,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 26,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 27,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 27,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 28,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 28,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 29,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 29,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 30,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 30,
                            ActorId = 8
                        });
                });

            modelBuilder.Entity("movie_rating_platform.Services.Database.MovieRating", b =>
                {
                    b.Property<int>("MovieRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieRatingId"));

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("MovieRatingId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieRatings");

                    b.HasData(
                        new
                        {
                            MovieRatingId = 1,
                            IsDeleted = false,
                            MovieId = 1,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 2,
                            IsDeleted = false,
                            MovieId = 1,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 3,
                            IsDeleted = false,
                            MovieId = 1,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 4,
                            IsDeleted = false,
                            MovieId = 2,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 5,
                            IsDeleted = false,
                            MovieId = 2,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 6,
                            IsDeleted = false,
                            MovieId = 2,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 7,
                            IsDeleted = false,
                            MovieId = 3,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 8,
                            IsDeleted = false,
                            MovieId = 3,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 9,
                            IsDeleted = false,
                            MovieId = 3,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 10,
                            IsDeleted = false,
                            MovieId = 4,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2
                        },
                        new
                        {
                            MovieRatingId = 11,
                            IsDeleted = false,
                            MovieId = 4,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 12,
                            IsDeleted = false,
                            MovieId = 4,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2
                        },
                        new
                        {
                            MovieRatingId = 13,
                            IsDeleted = false,
                            MovieId = 5,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 14,
                            IsDeleted = false,
                            MovieId = 5,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 15,
                            IsDeleted = false,
                            MovieId = 5,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 16,
                            IsDeleted = false,
                            MovieId = 6,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 17,
                            IsDeleted = false,
                            MovieId = 6,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 18,
                            IsDeleted = false,
                            MovieId = 6,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 19,
                            IsDeleted = false,
                            MovieId = 7,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 20,
                            IsDeleted = false,
                            MovieId = 7,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 21,
                            IsDeleted = false,
                            MovieId = 7,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 22,
                            IsDeleted = false,
                            MovieId = 8,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 23,
                            IsDeleted = false,
                            MovieId = 8,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 24,
                            IsDeleted = false,
                            MovieId = 8,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 25,
                            IsDeleted = false,
                            MovieId = 9,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 26,
                            IsDeleted = false,
                            MovieId = 9,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 27,
                            IsDeleted = false,
                            MovieId = 9,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 28,
                            IsDeleted = false,
                            MovieId = 10,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 29,
                            IsDeleted = false,
                            MovieId = 10,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 30,
                            IsDeleted = false,
                            MovieId = 10,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 31,
                            IsDeleted = false,
                            MovieId = 16,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 32,
                            IsDeleted = false,
                            MovieId = 16,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 33,
                            IsDeleted = false,
                            MovieId = 16,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 34,
                            IsDeleted = false,
                            MovieId = 17,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 35,
                            IsDeleted = false,
                            MovieId = 17,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 36,
                            IsDeleted = false,
                            MovieId = 17,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 37,
                            IsDeleted = false,
                            MovieId = 18,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 38,
                            IsDeleted = false,
                            MovieId = 18,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 39,
                            IsDeleted = false,
                            MovieId = 18,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 40,
                            IsDeleted = false,
                            MovieId = 19,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 41,
                            IsDeleted = false,
                            MovieId = 19,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 42,
                            IsDeleted = false,
                            MovieId = 19,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 43,
                            IsDeleted = false,
                            MovieId = 20,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 44,
                            IsDeleted = false,
                            MovieId = 20,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 45,
                            IsDeleted = false,
                            MovieId = 20,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 46,
                            IsDeleted = false,
                            MovieId = 21,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 47,
                            IsDeleted = false,
                            MovieId = 21,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 48,
                            IsDeleted = false,
                            MovieId = 21,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 49,
                            IsDeleted = false,
                            MovieId = 22,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 50,
                            IsDeleted = false,
                            MovieId = 22,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 51,
                            IsDeleted = false,
                            MovieId = 22,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 52,
                            IsDeleted = false,
                            MovieId = 23,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 53,
                            IsDeleted = false,
                            MovieId = 23,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 54,
                            IsDeleted = false,
                            MovieId = 23,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 55,
                            IsDeleted = false,
                            MovieId = 24,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 56,
                            IsDeleted = false,
                            MovieId = 24,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 57,
                            IsDeleted = false,
                            MovieId = 24,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 58,
                            IsDeleted = false,
                            MovieId = 25,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 59,
                            IsDeleted = false,
                            MovieId = 25,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 60,
                            IsDeleted = false,
                            MovieId = 25,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 61,
                            IsDeleted = false,
                            MovieId = 26,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 62,
                            IsDeleted = false,
                            MovieId = 26,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 63,
                            IsDeleted = false,
                            MovieId = 26,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 64,
                            IsDeleted = false,
                            MovieId = 27,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 65,
                            IsDeleted = false,
                            MovieId = 27,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 66,
                            IsDeleted = false,
                            MovieId = 27,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 67,
                            IsDeleted = false,
                            MovieId = 28,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 68,
                            IsDeleted = false,
                            MovieId = 28,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 69,
                            IsDeleted = false,
                            MovieId = 28,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 70,
                            IsDeleted = false,
                            MovieId = 29,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 71,
                            IsDeleted = false,
                            MovieId = 29,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            MovieRatingId = 72,
                            IsDeleted = false,
                            MovieId = 29,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 73,
                            IsDeleted = false,
                            MovieId = 30,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            MovieRatingId = 74,
                            IsDeleted = false,
                            MovieId = 30,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4
                        },
                        new
                        {
                            MovieRatingId = 75,
                            IsDeleted = false,
                            MovieId = 30,
                            RatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        });
                });

            modelBuilder.Entity("movie_rating_platform.Services.Database.MovieActor", b =>
                {
                    b.HasOne("movie_rating_platform.Services.Database.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_rating_platform.Services.Database.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("movie_rating_platform.Services.Database.MovieRating", b =>
                {
                    b.HasOne("movie_rating_platform.Services.Database.Movie", "Movie")
                        .WithMany("MovieRatings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("movie_rating_platform.Services.Database.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("movie_rating_platform.Services.Database.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
